[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =
    smoke: Smoke tests - teste critice, ruleaza rapid
    regression: Regression tests - suite completa
    api: API tests
    gui: GUI tests
addopts = --html=reports/report.html --self-contained-html
